### ISSUE TITLE
add emissions schedule with a function to read in the data

### ISSUE THREAD

**Issue by jalbrekt85** [BalancerMaxis/bal_tools#11]
emissions schedule: https://raw.githubusercontent.com/BalancerMaxis/bal_addresses/20774a49d71870ab1aba06cc0e93b3d16eef65c0/extras/emissions_per_year.json

ref: https://github.com/BalancerMaxis/bal_addresses/pull/302

**Comment by gosuto-inzasheru** [comment]
closed via 007458da77c9565b02bd775e6faacfc8139d27e8
