### ISSUE TITLE
fix: `TypeError: Object of type CorePools is not JSON serializable`

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/bal_tools#41]
corepools object cannot be dumped to json easily

**Comment by jalbrekt85** [comment]
the CorePools object shouldnt be serialized directly, there is CorePools.pools which contains the data and is just a typed dict

**Comment by jalbrekt85** [comment]
now implicitly json serializable, see - https://github.com/BalancerMaxis/bal_tools/pull/40#issuecomment-2372574009

**Comment by gosuto-inzasheru** [comment]
solved in https://github.com/BalancerMaxis/bal_tools/pull/40/
