### ISSUE TITLE
Add .chains to classes

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/bal_tools#8]
Should return at least somehow a list of available chain names, like in bal_addresses.  Right now it's hard to figure out what the options are.

**Comment by gosuto-inzasheru** [comment]
currently available as `Subgraph().chain`: https://github.com/BalancerMaxis/bal_tools/blob/0a5e15fd2998cf8cf7dc017ff40bab268d0a6c12/bal_tools/subgraph.py#L40

**Comment by gosuto-inzasheru** [comment]
or `BalPoolsGauges.chain`: https://github.com/BalancerMaxis/bal_tools/blob/0a5e15fd2998cf8cf7dc017ff40bab268d0a6c12/bal_tools/pools_gauges.py#L20
